# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bi8HH04GoTxQGOGQtWz1JG55FA3FvMCR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns



titanic_df = pd.read_csv('sample_data/train.csv')





titanic_df.head()

titanic_df.shape

titanic_df.drop(['PassengerId','Name','Ticket','Cabin'], 'columns',inplace=True)



titanic_df.head()

titanic_df[titanic_df.isnull().any(axis=1)].count()

titanic_df = titanic_df.dropna()



titanic_df.shape

titanic_df[titanic_df.isnull().any(axis=1)].count()

titanic_df.describe()



fig,ax = plt.subplots(figsize = (12,8))
plt.scatter(titanic_df['Age'], titanic_df['Survived'])
plt.xlabel('Age')
plt.ylabel('Survived')

pd.crosstab(titanic_df['Sex'], titanic_df['Survived'])

pd.crosstab(titanic_df['Pclass'], titanic_df['Survived'])

titanic_df_corr  =  titanic_df.corr()



titanic_df_corr

fig, ax = plt.subplots(figsize = (20,10))
sns.heatmap(titanic_df_corr, annot = True)

"""Data Preprocessing"""

from sklearn import preprocessing

label_encoding = preprocessing.LabelEncoder()
titanic_df['Sex'] = label_encoding.fit_transform(titanic_df['Sex'].astype(str))

titanic_df.head()

titanic_df = pd.get_dummies(titanic_df, columns = ['Embarked'])
titanic_df.head()

titanic_df = titanic_df.sample(frac=1).reset_index(drop=True)

titanic_df.head()

titanic_df.to_csv('sample_data/titanic_train_processed.csv', index=False)

:ls datasets



















